# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        thumb:
            quality: 100
            filters:
                thumbnail:
                    size: [150, 100]
                    mode: outbound
        echelle:
            quality: 100
            filters:
                scale:
                    dim: [250, 250]
        ad:
            quality: 100
            filters:
                upscale:   
                    min: [360, 230]
                thumbnail:
                    size: [360, 230]
                    mode: outbound              