vich_uploader:
    db_driver: orm

    mappings:
       post_images:
           uri_prefix: '%uploads_path%'
           upload_destination: '%kernel.project_dir%/public/%uploads_path%'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
       
